export const LOGIN = 'LOGIN';
export const LOGINEMPLOYEE = 'LOGINEMPLOYEE';
export const LISTACCOUNTS = 'LISTACCOUNTS';
export const ACTIVEACCOUNTS = 'ACTIVEACCOUNTS';
export const LISTCATEGORY = 'LISTCATEGORY';
export const LISTPRODUCTS = 'LISTPRODUCTS';
export const LISTDATASHEETS = 'LISTDATASHEETS';
export const ADDEDITDATASHEETS = 'ADDEDITDATASHEETS';
export const DELETEDATASHEETS = 'DELETEDATASHEETS';
export const LISTCATALOGUE = 'LISTCATALOGUE';
export const ADDEDITCATALOGUE = 'ADDEDITCATALOGUE';
export const DELETECATALOGUE = 'DELETECATALOGUE';
export const LISTFACTOR = 'LISTFACTOR';
export const ADDEDITFACTOR = 'ADDEDITFACTOR';
export const DELETEFACTOR = 'DELETEFACTOR';
export const LISTAGENT = 'LISTAGENT';
export const ADDEDITAGENT = 'ADDEDITAGENT';
export const DELETEAGENT = 'DELETEAGENT';
export const LISTPRICELST = 'LISTPRICELST';
export const LISTMESSAGES = 'LISTMESSAGES';
export const ADDEDITPRICELST = 'ADDEDITPRICELST';
export const DELETEPRICELST = 'DELETEPRICELST';
export const LISTCLIENTCOMM = 'LISTCLIENTCOMM';
export const ADDEDITClIENTCOMM = 'ADDEDITClIENTCOMM';
export const DELETEClIENTCOMM = 'DELETEClIENTCOMM';
export const COMPANYINFO = 'COMPANYINFO';
export const ADDEDITCOMPANYINFO = 'ADDEDITCOMPANYINFO';
export const GETALLCATEGORYTYPE = 'GETALLCATEGORYTYPE';
export const DELETECATEGORYTYPE = 'DELETECATEGORYTYPE';
export const ADDEDITCATEGORYTYPE = 'ADDEDITCATEGORYTYPE';
export const GETALLCATEGORYTYPEFORDROP = 'GETALLCATEGORYTYPEFORDROP';
export const GETALLCATEGORYGALLERY = 'GETALLCATEGORYGALLERY';
export const GETALLCATEGORYGALLERYFORDROP = 'GETALLCATEGORYGALLERYFORDROP';
export const ADDEDITCATEGORYGALLERY = 'ADDEDITCATEGORYGALLERY';
export const DELETECATEGORYGALLERY = 'DELETECATEGORYGALLERY';

export const GETALLCATEGORYCHILDGALLERY = 'GETALLCATEGORYCHILDGALLERY';
export const ADDEDITCATEGORYCHILDGALLERY = 'ADDEDITCATEGORYCHILDGALLERY';
export const DELETECATEGORYCHILDGALLERY = 'DELETECATEGORYCHILDGALLERY';
//??? ????????
export const ADDDEPOSIT = 'ADDDEPOSIT';
export const DECDEPOSIT = 'DECDEPOSIT';


export const GETALLCATEGORYCHILDGALLERYFORDROP = 'GETALLCATEGORYCHILDGALLERYFORDROP';
export const GALLERYType = 'GALLERYType';
export const ADDEDITGALLERY = 'ADDEDITGALLERY';
export const DELETEGALLERY = 'DELETEGALLERY';


export const GETALLCOLORS = 'GETALLCOLORS';
export const ADDEDITCOLORS = 'ADDEDITCOLORS';
export const DELETECOLORS = 'DELETECOLORS';



export const GETALLPARENTCATEGORY = 'GETALLPARENTCATEGORY';
export const ADDEDITPARENTCATEGORY = 'ADDEDITPARENTCATEGORY';
export const DELETEPARENTCATEGORY = 'DELETEPARENTCATEGORY';



export const GETALLPRODUCTNAME = 'GETALLPRODUCTNAME';
export const ADDEDITPRODUCTNAME = 'ADDEDITPRODUCTNAME';
export const DELETEPRODUCTNAME = 'DELETEPRODUCTNAME';


export const GETALLPARENTPRODUCTCATEGORY = 'GETALLPARENTPRODUCTCATEGORY';
export const ADDEDITPARENTPRODUCTCATEGORY = 'ADDEDITPARENTPRODUCTCATEGORY';
export const DELETEPARENTPRODUCTCATEGORY = 'DELETEPARENTPRODUCTCATEGORY';




export const GETALLPARENTPRODUCTCATEGORYFORDROP = 'GETALLPARENTPRODUCTCATEGORYFORDROP';
export const ADDEDITCATEGORY = 'ADDEDITCATEGORY';
export const DELETECATEGORY = 'DELETECATEGORY';
export const GETALLCATEGORY = 'GETALLCATEGORY';

export const PRODUCTFORDROP = 'PRODUCTFORDROP';
export const COLORSFORDROP = 'COLORSFORDROP';
export const CATEGORYFORDROP = 'CATEGORYFORDROP';
export const GETALLPRODUCT = 'GETALLPRODUCT';
export const ADDEDITPRODUCT = 'ADDEDITPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';




export const PARENTCATEGORY = 'PARENTCATEGORY';
export const GETALLSUBCATEGORY = 'GETALLSUBCATEGORY';
export const ADDEDITSUBCATEGORY = 'ADDEDITSUBCATEGORY';
export const DELETESUBCATEGORY = 'DELETESUBCATEGORY';

export const GETSUBCATEGORYFORDROP = 'GETSUBCATEGORYFORDROP';
export const GETPRODUCTFORDROP = 'GETPRODUCTFORDROP';


export const ADDEDITPRODUCTING = 'ADDEDITPRODUCTING';
export const DELETEPRODUCTING = 'DELETEPRODUCTING';
export const GETALLPRODUCTING = 'GETALLPRODUCTING';
export const GETPARENTPRODUCTFORDROP = 'GETPARENTPRODUCTFORDROP';
export const GETALLDESCOUNT = 'GETALLDESCOUNT';
export const ADDEDITDESCOUNT = 'ADDEDITDESCOUNT';
export const DELETEDESCOUNT = 'DELETEDESCOUNT';

export const GETALLINGREACCESS = 'GETALLINGREACCESS';
export const ADDEDITINGREACCESS = 'ADDEDITINGREACCESS';
export const DELETEINGREACCESS = 'DELETEINGREACCESS';

//suppliers
export const LISTSUPPLIER = 'LISTSUPPLIER';
export const LISTSUPPLIERFORDROP = 'LISTSUPPLIERFORDROP';
export const ADDEDITSUPPLIER = 'ADDEDISUPPLIER';
export const DELETESUPPLIER = 'DELETESUPPLIER';
export const COUNTSUPPLIER = 'COUNTSUPPLIER';
//Store
export const LISTSTORE = 'LISTSTORE';
export const LISTSTOREFORDROP = 'LISTSTOREFORDROP';
export const ADDEDITSTORE = 'ADDEDITSTORE';
export const DELETESTORE = 'DELETESTORE';
//ItemType
export const LISTITEMTYPE = 'LISTITEMTYPE';
export const LISTITEMTYPEFORDROP = 'LISTITEMTYPEFORDROP';
export const ADDEDITITEMTYPE = 'ADDEDITITEMTYPE';
export const DELETEITEMTYPE = 'DELETEITEMTYPE';
//Currency
export const LISTCURRENCY = 'LISTCURRENCY';
export const LISTCURRENCYFORDROP = 'LISTCURRENCYFORDROP';
export const ADDEDITCURRENCY = 'ADDEDITCURRENCY';
export const DELETEITCURRENCY = 'DELETEITCURRENCY';
//Bank
export const LISTBANK = 'LISTBANK';
export const ADDEDITBANK = 'ADDEDITBANK';
export const DELETEBANK = 'DELETEBANK';
export const LISTBANKDROPDOWN = 'LISTBANKDROPDOWN';

//Purchase
export const LISTPURCHASE = 'LISTPURCHASE';
export const ADDEDITPURCHASE = 'ADDEDITPURCHASE';
export const DELETEPURCHASE = 'DELETEPURCHASE';
//banks
export const LISTBANKOut = 'LISTBANKOut';
export const LISTBANKOutDROP = 'LISTBANKOutDROP';
export const ADDEDITBANKOut = 'ADDEDITBANKOut';
export const DELETEBANKOut = 'DELETEBANKOut';
//PAYMENT
export const LISTPAYMENT = 'LISTPAYMENT';
export const LISTPAYMENTFORDROP = 'LISTPAYMENTFORDROP';
//accounts
export const LISTACCOUNTSACTIVENOTACTIVE = 'LISTACCOUNTSACTIVENOTACTIVE';
export const RESETPASSWORD = 'RESETPASSWORD';
//Employee
export const LISTEMPLOYEE = 'LISTEMPLOYEE';
export const ADDEDITEMPLOYEE = 'ADDEDITEMPLOYEE';
export const DELETEEMPLOYEE = 'DELETEEMPLOYEE';
//ROLE
export const LISTROLEDD = 'LISTROLEDD';
